#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: pullrepos /path/to/dir" >&2
  exit 1
fi

for d in $1/*; do
  cd $d
  if [ -e .git ]; then
    echo $d:
    git pull origin master
  fi
  cd - >&2 > /dev/null
done

